### PR TITLE
Make bamboo trunks climbable

### PR DESCRIPTION
**Pull request by 6r1d**
Hello. Bamboo trunks look wide enough so character can climb those. So why not? :-)

### CODE REVIEW

**Comment by runsy** [comment]
Good idea. I will change it.

**Comment by mk-pmb** [comment]
Any progress on this? How can I help with it?

**Comment by 6r1d** [comment]
Hello, @mk-pmb.
I'm not sure I remember it all clearly, but we did [plant overrides for bamboos](https://github.com/pandorabox-io/pandorabox_custom/blob/eeb8f5f852c788bd6b77932afbc514df5ba0ff06/plant_overrides.lua) on PandoraBox.
If those aren't here, it'll be nice to backport that.

**Comment by mk-pmb** [comment]
Thanks! Let's hope @runsy is well and will have enough spare time soon to continue maintaining this project.

**Comment by runsy** [comment]
Done.

**Pull request closed without merging**
