### PR TITLE
Allowing generation of trees in v6 and floatlands

### PR DESCRIPTION
**Pull request by ChrysoliteAzalea**
I'd like to suggest all trees to be generated in v6 and floatlands.

### CODE REVIEW

**Comment by ChrysoliteAzalea** [comment]
The mapgen v7 has a feature called floatlands -- floating islands above y>1024 (depends on settings). I changed y_max to allow generation of trees in the floatlands.

**Comment by runsy** [comment]
I will rework this PR, to do not duplicate code.

1) Add a def with the common data for both mapgen versions.
2) If mapgen v7 the def would be def plus biomes.
3) Call the register_deco with the suitable def.

**Comment by mk-pmb** [comment]
Any progress on this? How can I help with it?

**Comment by ChrysoliteAzalea** [comment]
This pull request branch is 70 commits behind the base branch. The PR will be closed.

**Comment by runsy** [comment]
fixed in the last commit.

**Pull request closed without merging**
