### PR TITLE
Add fences, fence rails, and fence gates from cool wood.

### PR DESCRIPTION
**Pull request by sfence**
Add fences, fence rails, and fence gates from cool wood.

### CODE REVIEW

**Comment by runsy** [comment]
What is "cool_fences" setting?

**Comment by sfence** [comment]
> What is "cool_fences" setting?

It allows fences to be disabled.

**Comment by runsy** [comment]
> 
> 
> > What is "cool_fences" setting?
> 
> It allows fences to be disabled.

The problem I see is that that setting has to be set to true to enable fences.

**Comment by sfence** [comment]
> > > What is "cool_fences" setting?
> > 
> > 
> > It allows fences to be disabled.
> 
> Really it is not optional. The problem I see is that that setting has to be set to true to enable fences.

There is a default value set to true in minetest.settings:get_bool function. So if the setting is not defined, true is returned.
I have tested it without defined settings, and it looks well.

**Pull request merged**
